.TH DIFFRACTOMETERALIGNMENT "1"
.SH NAME
diffractometeralignment \- Sardana diffractometer alignment GUI
.SH SYNOPSIS
.B diffractometeralignment
\fI\,<model> \/\fR[\fI\,door_name\/\fR]
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBdiffractometeralignment\fP command is the GUI application
for diffractometer alignment: h, k, l movements and scans, go to maximum, ...

The best source for information about the available options is
to run `diffractometeralignment --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
