.TH HKLSCAN "1"
.SH NAME
hklscan \- Sardana HKL scan GUI
.SH SYNOPSIS
.B hklscan
\fI\,<model> \/\fR[\fI\,door_name\/\fR]
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBhklscan\fP command is the GUI application for performing hkl scans.

The best source for information about the available options is
to run `hklscan --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.