.TH MACROEXECUTOR "1"
.SH NAME
macroexecutor \- Sardana  GUI application for executing macros
.SH SYNOPSIS
.B macroexecutor
\fI\,<model> \/\fR[\fI\,door_name\/\fR]
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBmacroexecutor\fP command is the GUI application for executing macros.

The best source for information about the available options is
to run `macroexecutor --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
