.TH MacroServer "1"
.SH NAME
MacroServer \- Sardana MacroServer Tango device server
.SH SYNOPSIS
.B MacroServer
\fI\,[instance_name] \/
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBMacroServer\fP command launches the Sardana MacroServer Tango
device server.

The best source for information about the available options is
to run `MacroServer --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.