.TH POOL "1"
.SH NAME
Pool \- Sardana Pool Tango device server
.SH SYNOPSIS
.B Pool
\fI\,[instance_name] \/
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBPool\fP command launches the Sardana Pool Tango device server.

The best source for information about the available options is
to run `Pool --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
