.TH SARDANA "1"
.SH NAME
Sardana \- Sardana Tango device server
.SH SYNOPSIS
.B Sardana
\fI\,[instance_name] \/
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBSardana\fP command launches the Sardana Tango device server.

The best source for information about the available options is
to run `Sardana --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
