.TH SARDANATESTSUITE "1"
.SH NAME
sardanatestsuite \- Sardana test suite
.SH SYNOPSIS
.B sardanatestsuite
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBsardanatestsuite\fP command launches the Sardana test suite.

The best source for information about the available options is
to run `sardanatestsuite --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
