.TH SPOCK "1"
.SH NAME
spock \- Sardana CLI application
.SH SYNOPSIS
.B spock
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBspock\fP command launches the Sardana CLI application based on IPython.

The best source for information about the available options is
to visit the Spock documentation: http://sardana-controls.org/users/spock.html.

For more information about the Sardana project, visit
http://sardana-controls.org.
