.TH UBMATRIX "1"
.SH NAME
ubmatrix \- Sardana  GUI application for setting diffractomer parameters
.SH SYNOPSIS
.B ubmatrix
\fI\,<model> \/\fR[\fI\,door_name\/\fR]
.SH DESCRIPTION
Sardana is a software suite for Supervision, Control and Data Acquisition
in scientific installations.

The \fBubmatrix\fP command is the GUI application for setting diffractometer
parameters: ubmatrix, lattice, reflections, ...

The best source for information about the available options is
to run `ubmatrix --help`.

For more information about the Sardana project, visit
http://sardana-controls.org.
