# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpTkPBCp.ui'
#
# Created: Fri Aug 16 12:41:02 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DiffractometerAlignment(object):
    def setupUi(self, DiffractometerAlignment):
        DiffractometerAlignment.setObjectName("DiffractometerAlignment")
        DiffractometerAlignment.resize(861, 662)
        self.line_2 = QtGui.QFrame(DiffractometerAlignment)
        self.line_2.setGeometry(QtCore.QRect(10, 190, 20, 171))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(DiffractometerAlignment)
        self.line_3.setGeometry(QtCore.QRect(70, 180, 761, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(DiffractometerAlignment)
        self.line_4.setGeometry(QtCore.QRect(820, 190, 20, 171))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtGui.QLabel(DiffractometerAlignment)
        self.label.setGeometry(QtCore.QRect(40, 180, 31, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(DiffractometerAlignment)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 61, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(DiffractometerAlignment)
        self.label_3.setGeometry(QtCore.QRect(200, 210, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(DiffractometerAlignment)
        self.label_4.setGeometry(QtCore.QRect(430, 210, 16, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(DiffractometerAlignment)
        self.label_5.setGeometry(QtCore.QRect(640, 210, 16, 17))
        self.label_5.setObjectName("label_5")
        self.taurusValueLineH = TaurusValueLineEdit(DiffractometerAlignment)
        self.taurusValueLineH.setGeometry(QtCore.QRect(160, 270, 91, 27))
        self.taurusValueLineH.setObjectName("taurusValueLineH")
        self.taurusValueLineK = TaurusValueLineEdit(DiffractometerAlignment)
        self.taurusValueLineK.setGeometry(QtCore.QRect(380, 270, 91, 27))
        self.taurusValueLineK.setObjectName("taurusValueLineK")
        self.taurusValueLineL = TaurusValueLineEdit(DiffractometerAlignment)
        self.taurusValueLineL.setGeometry(QtCore.QRect(590, 270, 91, 27))
        self.taurusValueLineL.setObjectName("taurusValueLineL")
        self.label_8 = QtGui.QLabel(DiffractometerAlignment)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 111, 17))
        self.label_8.setObjectName("label_8")
        self.line_5 = QtGui.QFrame(DiffractometerAlignment)
        self.line_5.setGeometry(QtCore.QRect(80, 20, 761, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtGui.QFrame(DiffractometerAlignment)
        self.line_6.setGeometry(QtCore.QRect(10, 30, 20, 101))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtGui.QFrame(DiffractometerAlignment)
        self.line_7.setGeometry(QtCore.QRect(20, 130, 811, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtGui.QFrame(DiffractometerAlignment)
        self.line_8.setGeometry(QtCore.QRect(820, 30, 20, 91))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_9 = QtGui.QLabel(DiffractometerAlignment)
        self.label_9.setGeometry(QtCore.QRect(40, 275, 61, 17))
        self.label_9.setObjectName("label_9")
        self.taurusLabelValueH = TaurusLabel(DiffractometerAlignment)
        self.taurusLabelValueH.setGeometry(QtCore.QRect(170, 240, 81, 19))
        self.taurusLabelValueH.setObjectName("taurusLabelValueH")
        self.taurusLabelValueK = TaurusLabel(DiffractometerAlignment)
        self.taurusLabelValueK.setGeometry(QtCore.QRect(390, 240, 81, 19))
        self.taurusLabelValueK.setObjectName("taurusLabelValueK")
        self.taurusLabelValueL = TaurusLabel(DiffractometerAlignment)
        self.taurusLabelValueL.setGeometry(QtCore.QRect(600, 240, 81, 19))
        self.taurusLabelValueL.setObjectName("taurusLabelValueL")
        self.label_10 = QtGui.QLabel(DiffractometerAlignment)
        self.label_10.setGeometry(QtCore.QRect(40, 370, 111, 17))
        self.label_10.setObjectName("label_10")
        self.line_9 = QtGui.QFrame(DiffractometerAlignment)
        self.line_9.setGeometry(QtCore.QRect(90, 370, 741, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtGui.QFrame(DiffractometerAlignment)
        self.line_10.setGeometry(QtCore.QRect(20, 560, 811, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtGui.QFrame(DiffractometerAlignment)
        self.line_11.setGeometry(QtCore.QRect(10, 380, 20, 191))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtGui.QFrame(DiffractometerAlignment)
        self.line_12.setGeometry(QtCore.QRect(820, 380, 20, 191))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_13 = QtGui.QLabel(DiffractometerAlignment)
        self.label_13.setGeometry(QtCore.QRect(610, 320, 41, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(DiffractometerAlignment)
        self.label_14.setGeometry(QtCore.QRect(430, 320, 61, 17))
        self.label_14.setObjectName("label_14")
        self.taurusLabelEngine = TaurusLabel(DiffractometerAlignment)
        self.taurusLabelEngine.setGeometry(QtCore.QRect(490, 320, 91, 19))
        self.taurusLabelEngine.setObjectName("taurusLabelEngine")
        self.taurusLabelEngineMode = TaurusLabel(DiffractometerAlignment)
        self.taurusLabelEngineMode.setGeometry(QtCore.QRect(660, 320, 161, 19))
        self.taurusLabelEngineMode.setObjectName("taurusLabelEngineMode")
        self.label_15 = QtGui.QLabel(DiffractometerAlignment)
        self.label_15.setGeometry(QtCore.QRect(40, 320, 91, 17))
        self.label_15.setObjectName("label_15")
        self.AlignmentStopButton = QtGui.QPushButton(DiffractometerAlignment)
        self.AlignmentStopButton.setGeometry(QtCore.QRect(50, 620, 106, 26))
        self.AlignmentStopButton.setObjectName("AlignmentStopButton")
        self.MacroServerConnectionButton = QtGui.QPushButton(DiffractometerAlignment)
        self.MacroServerConnectionButton.setGeometry(QtCore.QRect(660, 620, 191, 26))
        self.MacroServerConnectionButton.setObjectName("MacroServerConnectionButton")
        self.line_13 = QtGui.QFrame(DiffractometerAlignment)
        self.line_13.setGeometry(QtCore.QRect(20, 350, 811, 20))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_6 = QtGui.QLabel(DiffractometerAlignment)
        self.label_6.setGeometry(QtCore.QRect(40, 55, 61, 17))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtGui.QLabel(DiffractometerAlignment)
        self.label_16.setGeometry(QtCore.QRect(40, 100, 61, 17))
        self.label_16.setObjectName("label_16")
        self.AlignmentStoreReflectionButton = QtGui.QPushButton(DiffractometerAlignment)
        self.AlignmentStoreReflectionButton.setGeometry(QtCore.QRect(180, 620, 106, 26))
        self.AlignmentStoreReflectionButton.setObjectName("AlignmentStoreReflectionButton")
        self.label_execscan = QtGui.QLabel(DiffractometerAlignment)
        self.label_execscan.setGeometry(QtCore.QRect(40, 410, 81, 17))
        self.label_execscan.setObjectName("label_execscan")
        self.label_range = QtGui.QLabel(DiffractometerAlignment)
        self.label_range.setGeometry(QtCore.QRect(40, 445, 51, 16))
        self.label_range.setObjectName("label_range")
        self.label_tomax = QtGui.QLabel(DiffractometerAlignment)
        self.label_tomax.setGeometry(QtCore.QRect(40, 480, 61, 16))
        self.label_tomax.setObjectName("label_tomax")
        self.label_nbpoints = QtGui.QLabel(DiffractometerAlignment)
        self.label_nbpoints.setGeometry(QtCore.QRect(70, 530, 71, 16))
        self.label_nbpoints.setObjectName("label_nbpoints")
        self.NbPointslineEdit = QtGui.QLineEdit(DiffractometerAlignment)
        self.NbPointslineEdit.setGeometry(QtCore.QRect(160, 525, 81, 27))
        self.NbPointslineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.NbPointslineEdit.setObjectName("NbPointslineEdit")
        self.SelectSignalButton = QtGui.QPushButton(DiffractometerAlignment)
        self.SelectSignalButton.setGeometry(QtCore.QRect(700, 530, 106, 26))
        self.SelectSignalButton.setObjectName("SelectSignalButton")

        self.retranslateUi(DiffractometerAlignment)
        QtCore.QMetaObject.connectSlotsByName(DiffractometerAlignment)

    def retranslateUi(self, DiffractometerAlignment):
        DiffractometerAlignment.setWindowTitle(QtGui.QApplication.translate("DiffractometerAlignment", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DiffractometerAlignment", "hkl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DiffractometerAlignment", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DiffractometerAlignment", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DiffractometerAlignment", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Angles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Move to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Scans", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Engine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Select mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignmentStopButton.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.MacroServerConnectionButton.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Macroserver Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Move to:", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignmentStoreReflectionButton.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Store Refl.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_execscan.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Exec Scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_range.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tomax.setText(QtGui.QApplication.translate("DiffractometerAlignment", "To Max.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nbpoints.setText(QtGui.QApplication.translate("DiffractometerAlignment", "Nb points:", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectSignalButton.setText(QtGui.QApplication.translate("DiffractometerAlignment", "SelectSignal", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DiffractometerAlignment = QtGui.TaurusWidget()
    ui = Ui_DiffractometerAlignment()
    ui.setupUi(DiffractometerAlignment)
    DiffractometerAlignment.show()
    sys.exit(app.exec_())

