# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpMlYPsy.ui'
#
# Created: Fri Aug  9 08:47:14 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ubmatrix(object):
    def setupUi(self, ubmatrix):
        ubmatrix.setObjectName("ubmatrix")
        ubmatrix.resize(809, 552)
        self.ub11label = QtGui.QLabel(ubmatrix)
        self.ub11label.setGeometry(QtCore.QRect(40, 40, 41, 17))
        self.ub11label.setObjectName("ub11label")
        self.taurusub11value = TaurusValueLineEdit(ubmatrix)
        self.taurusub11value.setGeometry(QtCore.QRect(100, 30, 148, 27))
        self.taurusub11value.setReadOnly(True)
        self.taurusub11value.setObjectName("taurusub11value")
        self.UpdateButton = QtGui.QPushButton(ubmatrix)
        self.UpdateButton.setGeometry(QtCore.QRect(20, 520, 106, 26))
        self.UpdateButton.setObjectName("UpdateButton")
        self.ub12label = QtGui.QLabel(ubmatrix)
        self.ub12label.setGeometry(QtCore.QRect(290, 40, 41, 17))
        self.ub12label.setObjectName("ub12label")
        self.ub13label = QtGui.QLabel(ubmatrix)
        self.ub13label.setGeometry(QtCore.QRect(510, 40, 41, 17))
        self.ub13label.setObjectName("ub13label")
        self.ub21label = QtGui.QLabel(ubmatrix)
        self.ub21label.setGeometry(QtCore.QRect(40, 80, 41, 17))
        self.ub21label.setObjectName("ub21label")
        self.ub22label = QtGui.QLabel(ubmatrix)
        self.ub22label.setGeometry(QtCore.QRect(290, 80, 41, 17))
        self.ub22label.setObjectName("ub22label")
        self.ub23label = QtGui.QLabel(ubmatrix)
        self.ub23label.setGeometry(QtCore.QRect(510, 80, 41, 17))
        self.ub23label.setObjectName("ub23label")
        self.ub31label = QtGui.QLabel(ubmatrix)
        self.ub31label.setGeometry(QtCore.QRect(40, 120, 41, 17))
        self.ub31label.setObjectName("ub31label")
        self.ub32label = QtGui.QLabel(ubmatrix)
        self.ub32label.setGeometry(QtCore.QRect(290, 120, 41, 17))
        self.ub32label.setObjectName("ub32label")
        self.ub33label = QtGui.QLabel(ubmatrix)
        self.ub33label.setGeometry(QtCore.QRect(510, 120, 41, 17))
        self.ub33label.setObjectName("ub33label")
        self.taurusub12value = TaurusValueLineEdit(ubmatrix)
        self.taurusub12value.setGeometry(QtCore.QRect(340, 30, 148, 27))
        self.taurusub12value.setReadOnly(True)
        self.taurusub12value.setObjectName("taurusub12value")
        self.taurusub13value = TaurusValueLineEdit(ubmatrix)
        self.taurusub13value.setGeometry(QtCore.QRect(570, 30, 148, 27))
        self.taurusub13value.setReadOnly(True)
        self.taurusub13value.setObjectName("taurusub13value")
        self.taurusub21value = TaurusValueLineEdit(ubmatrix)
        self.taurusub21value.setGeometry(QtCore.QRect(100, 70, 148, 27))
        self.taurusub21value.setReadOnly(True)
        self.taurusub21value.setObjectName("taurusub21value")
        self.taurusub22value = TaurusValueLineEdit(ubmatrix)
        self.taurusub22value.setGeometry(QtCore.QRect(340, 70, 148, 27))
        self.taurusub22value.setReadOnly(True)
        self.taurusub22value.setObjectName("taurusub22value")
        self.taurusub23value = TaurusValueLineEdit(ubmatrix)
        self.taurusub23value.setGeometry(QtCore.QRect(570, 70, 148, 27))
        self.taurusub23value.setReadOnly(True)
        self.taurusub23value.setObjectName("taurusub23value")
        self.taurusub31value = TaurusValueLineEdit(ubmatrix)
        self.taurusub31value.setGeometry(QtCore.QRect(100, 110, 148, 27))
        self.taurusub31value.setReadOnly(True)
        self.taurusub31value.setObjectName("taurusub31value")
        self.taurusub32value = TaurusValueLineEdit(ubmatrix)
        self.taurusub32value.setGeometry(QtCore.QRect(340, 110, 148, 27))
        self.taurusub32value.setReadOnly(True)
        self.taurusub32value.setObjectName("taurusub32value")
        self.taurusub33value = TaurusValueLineEdit(ubmatrix)
        self.taurusub33value.setGeometry(QtCore.QRect(570, 110, 148, 27))
        self.taurusub33value.setReadOnly(True)
        self.taurusub33value.setObjectName("taurusub33value")
        self.ComputeUButton = QtGui.QPushButton(ubmatrix)
        self.ComputeUButton.setGeometry(QtCore.QRect(140, 520, 106, 26))
        self.ComputeUButton.setObjectName("ComputeUButton")
        self.line = QtGui.QFrame(ubmatrix)
        self.line.setGeometry(QtCore.QRect(0, 140, 801, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.taurusuxeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusuxeditvalue.setGeometry(QtCore.QRect(100, 230, 148, 27))
        self.taurusuxeditvalue.setObjectName("taurusuxeditvalue")
        self.taurusuyeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusuyeditvalue.setGeometry(QtCore.QRect(340, 230, 148, 27))
        self.taurusuyeditvalue.setObjectName("taurusuyeditvalue")
        self.uxlabel = QtGui.QLabel(ubmatrix)
        self.uxlabel.setGeometry(QtCore.QRect(40, 210, 41, 17))
        self.uxlabel.setObjectName("uxlabel")
        self.taurusuzeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusuzeditvalue.setGeometry(QtCore.QRect(570, 230, 148, 27))
        self.taurusuzeditvalue.setObjectName("taurusuzeditvalue")
        self.uylabel = QtGui.QLabel(ubmatrix)
        self.uylabel.setGeometry(QtCore.QRect(290, 210, 41, 17))
        self.uylabel.setObjectName("uylabel")
        self.uzlabel = QtGui.QLabel(ubmatrix)
        self.uzlabel.setGeometry(QtCore.QRect(520, 210, 41, 17))
        self.uzlabel.setObjectName("uzlabel")
        self.line_2 = QtGui.QFrame(ubmatrix)
        self.line_2.setGeometry(QtCore.QRect(0, 270, 801, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ublabel = QtGui.QLabel(ubmatrix)
        self.ublabel.setGeometry(QtCore.QRect(30, 10, 71, 17))
        self.ublabel.setObjectName("ublabel")
        self.uvector_label = QtGui.QLabel(ubmatrix)
        self.uvector_label.setGeometry(QtCore.QRect(30, 170, 71, 17))
        self.uvector_label.setObjectName("uvector_label")
        self.lattice_label = QtGui.QLabel(ubmatrix)
        self.lattice_label.setGeometry(QtCore.QRect(30, 290, 71, 17))
        self.lattice_label.setObjectName("lattice_label")
        self.a_lattice_label = QtGui.QLabel(ubmatrix)
        self.a_lattice_label.setGeometry(QtCore.QRect(40, 330, 21, 20))
        self.a_lattice_label.setObjectName("a_lattice_label")
        self.b_lattice_label = QtGui.QLabel(ubmatrix)
        self.b_lattice_label.setGeometry(QtCore.QRect(280, 330, 21, 20))
        self.b_lattice_label.setObjectName("b_lattice_label")
        self.c_lattice_label = QtGui.QLabel(ubmatrix)
        self.c_lattice_label.setGeometry(QtCore.QRect(510, 330, 21, 20))
        self.c_lattice_label.setObjectName("c_lattice_label")
        self.alpha_lattice_label = QtGui.QLabel(ubmatrix)
        self.alpha_lattice_label.setGeometry(QtCore.QRect(40, 390, 41, 20))
        self.alpha_lattice_label.setObjectName("alpha_lattice_label")
        self.beta_lattice_label = QtGui.QLabel(ubmatrix)
        self.beta_lattice_label.setGeometry(QtCore.QRect(280, 390, 41, 20))
        self.beta_lattice_label.setObjectName("beta_lattice_label")
        self.gamma_lattice_label = QtGui.QLabel(ubmatrix)
        self.gamma_lattice_label.setGeometry(QtCore.QRect(510, 390, 61, 20))
        self.gamma_lattice_label.setObjectName("gamma_lattice_label")
        self.taurusalatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusalatticeeditvalue.setGeometry(QtCore.QRect(100, 340, 148, 27))
        self.taurusalatticeeditvalue.setObjectName("taurusalatticeeditvalue")
        self.taurusblatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusblatticeeditvalue.setGeometry(QtCore.QRect(340, 340, 148, 27))
        self.taurusblatticeeditvalue.setObjectName("taurusblatticeeditvalue")
        self.taurusclatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusclatticeeditvalue.setGeometry(QtCore.QRect(570, 340, 148, 27))
        self.taurusclatticeeditvalue.setObjectName("taurusclatticeeditvalue")
        self.taurusalphalatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusalphalatticeeditvalue.setGeometry(QtCore.QRect(100, 400, 148, 27))
        self.taurusalphalatticeeditvalue.setObjectName("taurusalphalatticeeditvalue")
        self.taurusbetalatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusbetalatticeeditvalue.setGeometry(QtCore.QRect(340, 400, 148, 27))
        self.taurusbetalatticeeditvalue.setObjectName("taurusbetalatticeeditvalue")
        self.taurusgammalatticeeditvalue = TaurusValueLineEdit(ubmatrix)
        self.taurusgammalatticeeditvalue.setGeometry(QtCore.QRect(570, 400, 148, 27))
        self.taurusgammalatticeeditvalue.setObjectName("taurusgammalatticeeditvalue")
        self.line_3 = QtGui.QFrame(ubmatrix)
        self.line_3.setGeometry(QtCore.QRect(0, 420, 801, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ReflectionsListButton = QtGui.QPushButton(ubmatrix)
        self.ReflectionsListButton.setGeometry(QtCore.QRect(260, 520, 111, 26))
        self.ReflectionsListButton.setObjectName("ReflectionsListButton")
        self.taurusuxvalue = TaurusLabel(ubmatrix)
        self.taurusuxvalue.setGeometry(QtCore.QRect(100, 200, 148, 20))
        self.taurusuxvalue.setObjectName("taurusuxvalue")
        self.taurusuyvalue = TaurusLabel(ubmatrix)
        self.taurusuyvalue.setGeometry(QtCore.QRect(340, 200, 148, 20))
        self.taurusuyvalue.setObjectName("taurusuyvalue")
        self.taurusuzvalue = TaurusLabel(ubmatrix)
        self.taurusuzvalue.setGeometry(QtCore.QRect(570, 200, 148, 20))
        self.taurusuzvalue.setObjectName("taurusuzvalue")
        self.taurusalatticevalue = TaurusLabel(ubmatrix)
        self.taurusalatticevalue.setGeometry(QtCore.QRect(100, 320, 148, 20))
        self.taurusalatticevalue.setObjectName("taurusalatticevalue")
        self.taurusblatticevalue = TaurusLabel(ubmatrix)
        self.taurusblatticevalue.setGeometry(QtCore.QRect(340, 320, 148, 20))
        self.taurusblatticevalue.setObjectName("taurusblatticevalue")
        self.taurusclatticevalue = TaurusLabel(ubmatrix)
        self.taurusclatticevalue.setGeometry(QtCore.QRect(570, 320, 148, 20))
        self.taurusclatticevalue.setObjectName("taurusclatticevalue")
        self.taurusalphalatticevalue = TaurusLabel(ubmatrix)
        self.taurusalphalatticevalue.setGeometry(QtCore.QRect(100, 380, 148, 20))
        self.taurusalphalatticevalue.setObjectName("taurusalphalatticevalue")
        self.taurusbetalatticevalue = TaurusLabel(ubmatrix)
        self.taurusbetalatticevalue.setGeometry(QtCore.QRect(340, 380, 148, 20))
        self.taurusbetalatticevalue.setObjectName("taurusbetalatticevalue")
        self.taurusgammalatticevalue = TaurusLabel(ubmatrix)
        self.taurusgammalatticevalue.setGeometry(QtCore.QRect(570, 380, 148, 20))
        self.taurusgammalatticevalue.setObjectName("taurusgammalatticevalue")
        self.EditReflectionsButton = QtGui.QPushButton(ubmatrix)
        self.EditReflectionsButton.setGeometry(QtCore.QRect(390, 520, 111, 26))
        self.EditReflectionsButton.setObjectName("EditReflectionsButton")

        self.retranslateUi(ubmatrix)
        QtCore.QMetaObject.connectSlotsByName(ubmatrix)

    def retranslateUi(self, ubmatrix):
        ubmatrix.setWindowTitle(QtGui.QApplication.translate("ubmatrix", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.ub11label.setText(QtGui.QApplication.translate("ubmatrix", "UB11", None, QtGui.QApplication.UnicodeUTF8))
        self.UpdateButton.setText(QtGui.QApplication.translate("ubmatrix", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.ub12label.setText(QtGui.QApplication.translate("ubmatrix", "UB12", None, QtGui.QApplication.UnicodeUTF8))
        self.ub13label.setText(QtGui.QApplication.translate("ubmatrix", "UB13", None, QtGui.QApplication.UnicodeUTF8))
        self.ub21label.setText(QtGui.QApplication.translate("ubmatrix", "UB21", None, QtGui.QApplication.UnicodeUTF8))
        self.ub22label.setText(QtGui.QApplication.translate("ubmatrix", "UB22", None, QtGui.QApplication.UnicodeUTF8))
        self.ub23label.setText(QtGui.QApplication.translate("ubmatrix", "UB23", None, QtGui.QApplication.UnicodeUTF8))
        self.ub31label.setText(QtGui.QApplication.translate("ubmatrix", "UB31", None, QtGui.QApplication.UnicodeUTF8))
        self.ub32label.setText(QtGui.QApplication.translate("ubmatrix", "UB32", None, QtGui.QApplication.UnicodeUTF8))
        self.ub33label.setText(QtGui.QApplication.translate("ubmatrix", "UB33", None, QtGui.QApplication.UnicodeUTF8))
        self.ComputeUButton.setText(QtGui.QApplication.translate("ubmatrix", "ComputeU", None, QtGui.QApplication.UnicodeUTF8))
        self.uxlabel.setText(QtGui.QApplication.translate("ubmatrix", "Ux", None, QtGui.QApplication.UnicodeUTF8))
        self.uylabel.setText(QtGui.QApplication.translate("ubmatrix", "Uy", None, QtGui.QApplication.UnicodeUTF8))
        self.uzlabel.setText(QtGui.QApplication.translate("ubmatrix", "Uz", None, QtGui.QApplication.UnicodeUTF8))
        self.ublabel.setText(QtGui.QApplication.translate("ubmatrix", "UB Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.uvector_label.setText(QtGui.QApplication.translate("ubmatrix", "U Vector", None, QtGui.QApplication.UnicodeUTF8))
        self.lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "Lattice", None, QtGui.QApplication.UnicodeUTF8))
        self.a_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.b_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.c_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.alpha_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.beta_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "beta", None, QtGui.QApplication.UnicodeUTF8))
        self.gamma_lattice_label.setText(QtGui.QApplication.translate("ubmatrix", "gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.ReflectionsListButton.setText(QtGui.QApplication.translate("ubmatrix", "Reflections List", None, QtGui.QApplication.UnicodeUTF8))
        self.EditReflectionsButton.setText(QtGui.QApplication.translate("ubmatrix", "Edit Reflections", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ubmatrix = QtGui.TaurusWidget()
    ui = Ui_ubmatrix()
    ui.setupUi(ubmatrix)
    ubmatrix.show()
    sys.exit(app.exec_())

