# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/tmp/tmpWZdtp5.ui'
#
# Created: Tue Aug  6 15:46:26 2013
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HKLScan(object):
    def setupUi(self, HKLScan):
        HKLScan.setObjectName("HKLScan")
        HKLScan.resize(848, 569)
        self.line = QtGui.QFrame(HKLScan)
        self.line.setGeometry(QtCore.QRect(20, 220, 811, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(HKLScan)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 20, 191))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(HKLScan)
        self.line_3.setGeometry(QtCore.QRect(140, 20, 691, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtGui.QFrame(HKLScan)
        self.line_4.setGeometry(QtCore.QRect(820, 30, 20, 201))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtGui.QLabel(HKLScan)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(HKLScan)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 61, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(HKLScan)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(HKLScan)
        self.label_4.setGeometry(QtCore.QRect(430, 50, 16, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(HKLScan)
        self.label_5.setGeometry(QtCore.QRect(640, 50, 16, 17))
        self.label_5.setObjectName("label_5")
        self.taurusValueLineH = TaurusValueLineEdit(HKLScan)
        self.taurusValueLineH.setGeometry(QtCore.QRect(160, 110, 91, 27))
        self.taurusValueLineH.setObjectName("taurusValueLineH")
        self.taurusValueLineK = TaurusValueLineEdit(HKLScan)
        self.taurusValueLineK.setGeometry(QtCore.QRect(380, 110, 91, 27))
        self.taurusValueLineK.setObjectName("taurusValueLineK")
        self.taurusValueLineL = TaurusValueLineEdit(HKLScan)
        self.taurusValueLineL.setGeometry(QtCore.QRect(590, 110, 91, 27))
        self.taurusValueLineL.setObjectName("taurusValueLineL")
        self.label_6 = QtGui.QLabel(HKLScan)
        self.label_6.setGeometry(QtCore.QRect(40, 160, 61, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(HKLScan)
        self.label_7.setGeometry(QtCore.QRect(40, 200, 61, 17))
        self.label_7.setObjectName("label_7")
        self.lineEditStartH = QtGui.QLineEdit(HKLScan)
        self.lineEditStartH.setGeometry(QtCore.QRect(160, 150, 91, 27))
        self.lineEditStartH.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStartH.setObjectName("lineEditStartH")
        self.lineEditStartL = QtGui.QLineEdit(HKLScan)
        self.lineEditStartL.setGeometry(QtCore.QRect(590, 150, 91, 27))
        self.lineEditStartL.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStartL.setObjectName("lineEditStartL")
        self.lineEditStartK = QtGui.QLineEdit(HKLScan)
        self.lineEditStartK.setGeometry(QtCore.QRect(380, 150, 91, 27))
        self.lineEditStartK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStartK.setObjectName("lineEditStartK")
        self.lineEditStopH = QtGui.QLineEdit(HKLScan)
        self.lineEditStopH.setGeometry(QtCore.QRect(160, 190, 91, 27))
        self.lineEditStopH.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStopH.setObjectName("lineEditStopH")
        self.lineEditStopK = QtGui.QLineEdit(HKLScan)
        self.lineEditStopK.setGeometry(QtCore.QRect(380, 190, 91, 27))
        self.lineEditStopK.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStopK.setObjectName("lineEditStopK")
        self.lineEditStopL = QtGui.QLineEdit(HKLScan)
        self.lineEditStopL.setGeometry(QtCore.QRect(590, 190, 91, 27))
        self.lineEditStopL.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStopL.setObjectName("lineEditStopL")
        self.label_8 = QtGui.QLabel(HKLScan)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 111, 17))
        self.label_8.setObjectName("label_8")
        self.line_5 = QtGui.QFrame(HKLScan)
        self.line_5.setGeometry(QtCore.QRect(70, 260, 761, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtGui.QFrame(HKLScan)
        self.line_6.setGeometry(QtCore.QRect(10, 260, 20, 101))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtGui.QFrame(HKLScan)
        self.line_7.setGeometry(QtCore.QRect(20, 340, 811, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtGui.QFrame(HKLScan)
        self.line_8.setGeometry(QtCore.QRect(820, 260, 20, 91))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_9 = QtGui.QLabel(HKLScan)
        self.label_9.setGeometry(QtCore.QRect(40, 120, 61, 17))
        self.label_9.setObjectName("label_9")
        self.taurusLabelValueH = TaurusLabel(HKLScan)
        self.taurusLabelValueH.setGeometry(QtCore.QRect(170, 80, 81, 19))
        self.taurusLabelValueH.setObjectName("taurusLabelValueH")
        self.taurusLabelValueK = TaurusLabel(HKLScan)
        self.taurusLabelValueK.setGeometry(QtCore.QRect(390, 80, 81, 19))
        self.taurusLabelValueK.setObjectName("taurusLabelValueK")
        self.taurusLabelValueL = TaurusLabel(HKLScan)
        self.taurusLabelValueL.setGeometry(QtCore.QRect(600, 80, 81, 19))
        self.taurusLabelValueL.setObjectName("taurusLabelValueL")
        self.label_10 = QtGui.QLabel(HKLScan)
        self.label_10.setGeometry(QtCore.QRect(40, 370, 111, 17))
        self.label_10.setObjectName("label_10")
        self.line_9 = QtGui.QFrame(HKLScan)
        self.line_9.setGeometry(QtCore.QRect(120, 370, 711, 20))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtGui.QFrame(HKLScan)
        self.line_10.setGeometry(QtCore.QRect(20, 470, 811, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtGui.QFrame(HKLScan)
        self.line_11.setGeometry(QtCore.QRect(10, 380, 20, 101))
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtGui.QFrame(HKLScan)
        self.line_12.setGeometry(QtCore.QRect(820, 380, 20, 101))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_11 = QtGui.QLabel(HKLScan)
        self.label_11.setGeometry(QtCore.QRect(180, 400, 71, 17))
        self.label_11.setObjectName("label_11")
        self.LineEditNbpoints = QtGui.QLineEdit(HKLScan)
        self.LineEditNbpoints.setGeometry(QtCore.QRect(270, 396, 81, 27))
        self.LineEditNbpoints.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LineEditNbpoints.setObjectName("LineEditNbpoints")
        self.label_12 = QtGui.QLabel(HKLScan)
        self.label_12.setGeometry(QtCore.QRect(410, 400, 101, 17))
        self.label_12.setObjectName("label_12")
        self.LineEditSampleTime = QtGui.QLineEdit(HKLScan)
        self.LineEditSampleTime.setGeometry(QtCore.QRect(520, 396, 81, 27))
        self.LineEditSampleTime.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.LineEditSampleTime.setObjectName("LineEditSampleTime")
        self.label_13 = QtGui.QLabel(HKLScan)
        self.label_13.setGeometry(QtCore.QRect(610, 450, 41, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(HKLScan)
        self.label_14.setGeometry(QtCore.QRect(430, 450, 61, 17))
        self.label_14.setObjectName("label_14")
        self.taurusLabelEngine = TaurusLabel(HKLScan)
        self.taurusLabelEngine.setGeometry(QtCore.QRect(490, 450, 91, 19))
        self.taurusLabelEngine.setObjectName("taurusLabelEngine")
        self.taurusLabelEngineMode = TaurusLabel(HKLScan)
        self.taurusLabelEngineMode.setGeometry(QtCore.QRect(660, 450, 161, 19))
        self.taurusLabelEngineMode.setObjectName("taurusLabelEngineMode")
        self.label_15 = QtGui.QLabel(HKLScan)
        self.label_15.setGeometry(QtCore.QRect(40, 450, 91, 17))
        self.label_15.setObjectName("label_15")
        self.hklStartScanButton = QtGui.QPushButton(HKLScan)
        self.hklStartScanButton.setGeometry(QtCore.QRect(90, 510, 106, 26))
        self.hklStartScanButton.setObjectName("hklStartScanButton")
        self.hklStopScanButton = QtGui.QPushButton(HKLScan)
        self.hklStopScanButton.setGeometry(QtCore.QRect(220, 510, 106, 26))
        self.hklStopScanButton.setObjectName("hklStopScanButton")
        self.MacroServerConnectionButton = QtGui.QPushButton(HKLScan)
        self.MacroServerConnectionButton.setGeometry(QtCore.QRect(640, 520, 191, 26))
        self.MacroServerConnectionButton.setObjectName("MacroServerConnectionButton")
        self.hklDisplayAnglesButton = QtGui.QPushButton(HKLScan)
        self.hklDisplayAnglesButton.setGeometry(QtCore.QRect(350, 510, 131, 26))
        self.hklDisplayAnglesButton.setObjectName("hklDisplayAnglesButton")

        self.retranslateUi(HKLScan)
        QtCore.QMetaObject.connectSlotsByName(HKLScan)

    def retranslateUi(self, HKLScan):
        HKLScan.setWindowTitle(QtGui.QApplication.translate("HKLScan", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HKLScan", "Positions/Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HKLScan", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("HKLScan", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HKLScan", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HKLScan", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("HKLScan", "Start:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("HKLScan", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("HKLScan", "Angles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("HKLScan", "Move to:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("HKLScan", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("HKLScan", "Nb points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("HKLScan", "Sample time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("HKLScan", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("HKLScan", "Engine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("HKLScan", "Select mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.hklStartScanButton.setText(QtGui.QApplication.translate("HKLScan", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.hklStopScanButton.setText(QtGui.QApplication.translate("HKLScan", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.MacroServerConnectionButton.setText(QtGui.QApplication.translate("HKLScan", "Macroserver Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.hklDisplayAnglesButton.setText(QtGui.QApplication.translate("HKLScan", "Display Angles", None, QtGui.QApplication.UnicodeUTF8))

from taurus.qt.qtgui.display import TaurusLabel
from taurus.qt.qtgui.container import TaurusWidget
from taurus.qt.qtgui.input import TaurusValueLineEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    HKLScan = QtGui.TaurusWidget()
    ui = Ui_HKLScan()
    ui.setupUi(HKLScan)
    HKLScan.show()
    sys.exit(app.exec_())

