name: CI tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: reszelaz/sardana-test
      options: -h sardana-test
    steps:  
    - uses: actions/checkout@v2
    - name: Install sardana
      run: python3 setup.py install
    - name: Start servers
      run: |
        /usr/bin/supervisord
        sleep 10
        supervisorctl start Pool
        supervisorctl start MacroServer
    - name: Run tests
      run: xvfb-run -s '-screen 0 1920x1080x24' /bin/bash -c "pytest /usr/local/lib/python3.5/dist-packages/sardana-*.egg/sardana"
  
